server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: blogs-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: directxjy921
mybatis:
  mapper-locations: classpath*:cn/xiaojunyun/cloud/blog/user/mapper/*.xml
  configuration:
    cache-enabled: true
logging:
  level:
    root: info
    cn.xiaojunyun.cloud.blog: debug
